// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/labstack/echo/v4"
	user4 "lazy/application/todo/commands/add_todo"
	user5 "lazy/application/todo/commands/complete_todo"
	"lazy/application/todo/queries/get_todos_user"
	"lazy/application/user/commands/register_user"
	user2 "lazy/application/user/queries/get_current_user"
	"lazy/infrastructure/config"
	local2 "lazy/infrastructure/local"
	local3 "lazy/infrastructure/local/todo"
	"lazy/infrastructure/local/user"
	todo2 "lazy/presentation/http/todo"
	user3 "lazy/presentation/http/user"
)

// Injectors from wire.go:

func InitializeApp() *echo.Echo {
	repository := local.NewUserRepository()
	unitOfWork := local2.NewUnitOfWork()
	env := config.NewEnv()
	handler := user.NewHandler(repository, unitOfWork, env)
	userHandler := user2.NewHandler(repository)
	controller := user3.NewController(handler, userHandler)
	todoRepository := local3.NewTodoRepository()
	todoHandler := todo.NewHandler(todoRepository, repository)
	handler2 := user4.NewHandler(todoRepository, unitOfWork)
	handler3 := user5.NewHandler(todoRepository, unitOfWork, env)
	todoController := todo2.NewController(todoHandler, handler2, handler3)
	mainController := Controller{
		User: controller,
		Todo: todoController,
	}
	echoEcho := NewApp(mainController)
	return echoEcho
}
